### ISSUE TITLE
Issue with Directory Path of the Project Folder

### ISSUE THREAD

**Issue by shivamsharmahere** [devang-bhardwaj/Youtube_Videos_and_Playlist_Downloader#1]
Actually everything is great , but just one thig is what I found to be corrected is - When we clone the repository the folder is created with name of 'Youtube_Videos_and_Playlist_Downloader' instead of 'youtube-downloader'.

So please just edit it for people to be more comfortable with the code. 

Thanks

![image](https://github.com/user-attachments/assets/514907ff-cdde-4b3c-90c9-8e176577d05c)

**Comment by devang-bhardwaj** [comment]
Thanks For Drawing my Attention To this Detail I Mistakenly Overlooked while pushing the code, I'll fix it ASAP!
